package edu.software.lms;

public enum SignUpResult {
    INVALID_PASSWORD,
    INVALID_USERNAME,
    PASSWORD_TOO_SHORT,
    PASSWORD_WEAK,
    USER_CREATED_SUCCESSFULLY,
    USER_CREATION_FAILED,
}
